### ISSUE TITLE
resolvePackageNotFound: - psycopg2==2.8.4=py37h1ba5d50_0

### ISSUE THREAD

**Issue by JasonWu0506** [Jamesyang2333/SAM#1]
following the README
on MacOS Montery 12.4
Apple M1 Pro

conda 4.13.0
/Users/{userid}/opt/anaconda3/bin/python

**Comment by Jamesyang2333** [comment]
Hi Jason, our setup uses conda 4.12.0 and it runs fine on Linux platform. Can you try degrade your conda to 4.12.0? If it still doesn't work maybe you can try a different version of psycopg2.

**Comment by JasonWu0506** [comment]
No luck...

**Comment by Jamesyang2333** [comment]
This issue is probably platform specific, as you use a M1 mac and unix platform. I would suggest running it on a Linux machine.
