### ISSUE TITLE
dependency lib failure

### ISSUE THREAD

**Issue by JasonWu0506** [Jamesyang2333/SAM#3]
![image](https://user-images.githubusercontent.com/104332592/185528033-34e41467-af18-4e13-8f6d-c9c3e54256d4.png)

**Comment by Jamesyang2333** [comment]
Hi Jason, the rustlib.so lib only works on Linux platform. Mac runs on Unix and has a different executable file format, as it shows "not a mach-o file". You may switch to a Linux machine and try again.
